version: '3'
services:
    nginx:
        image: nginx
        container_name: container-nginx
        #network_mode: host
        ports:
            - "80:80"
        volumes: 
            - ${app}/nginx:/etc/nginx
            - ${app}/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - django
            - nodejs
 
    mysql:
        image: mysql
        container_name: container-mysql
        #network_mode: host
        volumes: 
            - ${app}/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: example
            
    nodejs:
        build: 
            context: ${app}/client
            dockerfile: Dockerfile
        container_name: container-nodejs
        #network_mode: host
        ports:
            - "3000:3000"
        volumes:
            - ${app}/client:/app
    django:
        build:
            context: ${PREFIX}/app
            dockerfile: Dockerfile
        container_name: container-django

        ports:
            - "8000:8000"

        volumes:
            - ${app}/app:/app
        depends_on:
            - mysql

volumes:
    geoserver_data:
